// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-PaOMfDGKpOUUNteWZPtjr9Ph6Uq4hgo',
    appId: '1:169523719476:web:e90577d23c789b87248961',
    messagingSenderId: '169523719476',
    projectId: 'profil-klinikshoes',
    authDomain: 'profil-klinikshoes.firebaseapp.com',
    storageBucket: 'profil-klinikshoes.firebasestorage.app',
    measurementId: 'G-4Z68K38WXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpmbkQbW1zKWWGYHwlFPG8PGc-n3-uTeU',
    appId: '1:169523719476:android:345bd96d9a98db3c248961',
    messagingSenderId: '169523719476',
    projectId: 'profil-klinikshoes',
    storageBucket: 'profil-klinikshoes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdGv2CIoMdxEyOypBpjQYGkq4tAd7I-Wo',
    appId: '1:169523719476:ios:43ae3015c196a69c248961',
    messagingSenderId: '169523719476',
    projectId: 'profil-klinikshoes',
    storageBucket: 'profil-klinikshoes.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
